<a href="https://colab.research.google.com/github/niradaa-art/project_BP_group8/blob/main/Project_Colab_group8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Group 8 MONEY_knock_everyting
นางสาวณิรดา อนุนิวัฒน์ 673020252-4

นายธนพล ท้าวนอ 673020253-2

นางสาวสุพิชชา คำสิงห์ 673020265-5

นางสาวอาทิติญา ชาชัย 673020270-2

---

#Data
https://drive.google.com/drive/folders/1m6hp8l6iMB1u-a1yNK4laewgrUTy_Bnl?usp=drive_link

#Connect Google Drive

In [21]:
import os
from google.colab import drive
drive.mount('/content/drive')
base_path = '/content/drive/MyDrive/datasets_budget'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# ชุดข้อมูลที่ 1 รายการจัดสรรงบประมาณระดับจังหวัด ปีงบประมาณ พ.ศ.2566

In [22]:
import pandas as pd

budget = pd.read_csv(f"{base_path}/provincial_budget.csv", sep="|")
budget

,fy,changwad_area_name,min_name,agc_name,plan_name,output_name,objc,budget
0,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานยุทธศาสตร์พัฒนาระบบการเตรียมพร้อมแห่งชาต...,รายจ่ายงบกลาง : ค่าใช้จ่ายชดใช้เงินทดรองราชการ...,งบรายจ่ายอื่น,2000000000
1,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานพื้นฐานด้านความมั่นคง,รายจ่ายงบกลาง : ค่าใช้จ่ายเกี่ยวกับการเสด็จพระ...,งบดำเนินงาน,800000000
2,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานยุทธศาสตร์เสริมสร้างพลังทางสังคม,รายจ่ายงบกลาง : ค่าใช้จ่ายตามโครงการอันเนื่องม...,งบรายจ่ายอื่น,300000000
3,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานยุทธศาสตร์เสริมสร้างพลังทางสังคม,รายจ่ายงบกลาง : ค่าใช้จ่ายตามโครงการอันเนื่องม...,งบลงทุน,2000000000
4,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานยุทธศาสตร์สร้างหลักประกันทางสังคม,รายจ่ายงบกลาง : ค่าใช้จ่ายในการรักษาพยาบาลข้าร...,งบดำเนินงาน,76000000000
...,...,...,...,...,...,...,...,...
17403,66,จังหวัดนราธิวาส,จังหวัดและกลุ่มจังหวัด,กลุ่มจังหวัดภาคใต้ชายแดน,แผนงานยุทธศาสตร์ส่งเสริมการพัฒนาจังหวัดและกลุ่...,โครงการ : โครงการพัฒนาด้านสังคม,งบดำเนินงาน,475200
17404,66,จังหวัดนราธิวาส,องค์กรปกครองส่วนท้องถิ่น,องค์การบริหารส่วนจังหวัดนราธิวาส,แผนงานยุทธศาสตร์ส่งเสริมการกระจายอำนาจให้แก่อง...,ผลผลิต : ผลผลิตการจัดบริการสาธารณะ,งบอุดหนุน,107293900
17405,66,จังหวัดนราธิวาส,องค์กรปกครองส่วนท้องถิ่น,เทศบาลเมืองนราธิวาส,แผนงานยุทธศาสตร์ส่งเสริมการกระจายอำนาจให้แก่อง...,ผลผลิต : ผลผลิตการจัดบริการสาธารณะ,งบอุดหนุน,299211400
17406,66,จังหวัดนราธิวาส,องค์กรปกครองส่วนท้องถิ่น,เทศบาลเมืองตากใบ,แผนงานยุทธศาสตร์ส่งเสริมการกระจายอำนาจให้แก่อง...,ผลผลิต : ผลผลิตการจัดบริการสาธารณะ,งบอุดหนุน,73979500
17407,66,จังหวัดนราธิวาส,องค์กรปกครองส่วนท้องถิ่น,เทศบาลเมืองสุไหงโก-ลก,แผนงานยุทธศาสตร์ส่งเสริมการกระจายอำนาจให้แก่อง...,ผลผลิต : ผลผลิตการจัดบริการสาธารณะ,งบอุดหนุน,270340400

In [23]:
budget.shape

(17408, 8)

In [24]:
budget.columns

Index(['fy', 'changwad_area_name', 'min_name', 'agc_name', 'plan_name',
       'output_name', 'objc', 'budget'],
      dtype='object')

In [25]:
budget.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17408 entries, 0 to 17407
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   fy                  17408 non-null  int64
 1   changwad_area_name  17408 non-null  object
 2   min_name            17408 non-null  object
 3   agc_name            17408 non-null  object
 4   plan_name           17408 non-null  object
 5   output_name         17408 non-null  object
 6   objc                17408 non-null  object
 7   budget              17408 non-null  int64
dtypes: int64(2), object(6)
memory usage: 1.1+ MB

# ชุดข้อมูลที่ 2 ผลิตภัณฑ์มวลรวมของประเทศ

In [47]:
import pandas as pd

gpp = pd.read_csv(f"{base_path}/gdp.csv")
gpp

,TIME_PERIOD,NA_STAT,NI,AREA,CWT,UNIT_MUL,UNIT,FREQ,Value
0,2538,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์มวลรวมจังหวัด (GPP),ภาคกลาง,ลพบุรี,ล้าน,บาท,รายปี,31670.73332
1,2539,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์มวลรวมจังหวัด (GPP),ภาคกลาง,ลพบุรี,ล้าน,บาท,รายปี,37846.85892
2,2540,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์มวลรวมจังหวัด (GPP),ภาคกลาง,ลพบุรี,ล้าน,บาท,รายปี,37509.20217
3,2541,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์มวลรวมจังหวัด (GPP),ภาคกลาง,ลพบุรี,ล้าน,บาท,รายปี,36383.28861
4,2542,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์มวลรวมจังหวัด (GPP),ภาคกลาง,ลพบุรี,ล้าน,บาท,รายปี,34062.19292
...,...,...,...,...,...,...,...,...,...
7390,2562,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์จังหวัด (GPP) ต่อหัว,ภาคใต้,ตรัง,หน่วย,บาท,รายปี,99096.54000
7391,2563,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์จังหวัด (GPP) ต่อหัว,ภาคใต้,ตรัง,หน่วย,บาท,รายปี,102199.13000
7392,2564,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์จังหวัด (GPP) ต่อหัว,ภาคใต้,ตรัง,หน่วย,บาท,รายปี,109718.64000
7393,2565,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์จังหวัด (GPP) ต่อหัว,ภาคใต้,ตรัง,หน่วย,บาท,รายปี,117894.33400
7394,2566,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์จังหวัด (GPP) ต่อหัว,ภาคใต้,ตรัง,หน่วย,บาท,รายปี,111746.19100

In [48]:
gpp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7395 entries, 0 to 7394
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TIME_PERIOD  7395 non-null   int64
 1   NA_STAT      7395 non-null   object
 2   NI           7395 non-null   object
 3   AREA         7395 non-null   object
 4   CWT          7395 non-null   object
 5   UNIT_MUL     7395 non-null   object
 6   UNIT         7395 non-null   object
 7   FREQ         7395 non-null   object
 8   Value        7395 non-null   float64
dtypes: float64(1), int64(1), object(7)
memory usage: 520.1+ KB

# ชุดข้อมูลชุดที่ 3 รายชื่อพรรคการเมืองระดับจังหวัด

In [28]:
import pandas as pd

party = pd.read_csv(f"{base_path}/partylist.csv")
party

        changwad_area_name    party_name
0            จังหวัดกระบี่     ภูมิใจไทย
1            กรุงเทพมหานคร       ก้าวไกล
2         จังหวัดกาญจนบุรี      เพื่อไทย
3         จังหวัดกาฬสินธุ์      เพื่อไทย
4         จังหวัดกำแพงเพชร  พลังประชารัฐ
..                     ...           ...
72        จังหวัดเพชรบูรณ์  พลังประชารัฐ
73              จังหวัดเลย      เพื่อไทย
74             จังหวัดแพร่      เพื่อไทย
75       จังหวัดแม่ฮ่องสอน  ประชาธิปัตย์
76  จังหวัดพระนครศรีอยุธยา     ภูมิใจไทย

[77 rows x 2 columns]

In [29]:
party.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   changwad_area_name  77 non-null     object
 1   party_name          77 non-null     object
dtypes: object(2)
memory usage: 1.3+ KB

# Clean Data

##ตรวจสอบ Missing Values

In [30]:
budget.isnull().sum()

fy                    0
changwad_area_name    0
min_name              0
agc_name              0
plan_name             0
output_name           0
objc                  0
budget                0
dtype: int64

##ตรวจสอบ Duplicate

In [31]:
budget.duplicated().sum()

np.int64(1)

In [35]:
budget[budget.duplicated()]
#-----------------------------------------------
#รายการงบประมาณที่มีข้อมูลเหมือนกันอาจเป็นรายการงบประมาณคนละรายการจริง ๆ
#-----------------------------------------------

,fy,changwad_area_name,min_name,agc_name,plan_name,output_name,objc,budget
13,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานบริหารเพื่อรองรับกรณีฉุกเฉินหรือจำเป็น,รายจ่ายงบกลาง : เงินสำรองจ่ายเพื่อกรณีฉุกเฉินห...,งบลงทุน,27720000000

##ตรวจสอบข้อมูลผิดปกติ

In [36]:
#ตรวจสอบ columm budget
df["budget"].describe()

count    1.740800e+04
mean     1.828848e+08
std      4.147141e+09
min      1.100000e+03
25%      1.020000e+06
50%      5.856850e+06
75%      3.384408e+07
max      3.227900e+11
Name: budget, dtype: float64

In [37]:
#งบประมาณมีการกระจายค่อนข้างกว้าง
#ตรวจสอบค่า Budget ที่สูงมากก่อนทำ Visualization
df.sort_values("budget", ascending=False).head(10)

,fy,changwad_area_name,min_name,agc_name,plan_name,output_name,objc,budget
5,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานพื้นฐานด้านการปรับสมดุลและพัฒนาระบบการบร...,รายจ่ายงบกลาง : เงินเบี้ยหวัด บำเหน็จ บำนาญ,งบอุดหนุน,322790000000
6916,66,กรุงเทพมหานคร,กระทรวงการคลัง,สำนักงานบริหารหนี้สาธารณะ,แผนงานบริหารจัดการหนี้ภาครัฐ,ผลผลิต : การบริหารการชำระหนี้ของรัฐบาล,งบรายจ่ายอื่น,261756426300
8602,66,กรุงเทพมหานคร,กระทรวงมหาดไทย,กรมส่งเสริมการปกครองท้องถิ่น,แผนงานยุทธศาสตร์ส่งเสริมการกระจายอำนาจให้แก่อง...,ผลผลิต : จัดสรรเงินอุดหนุนให้แก่องค์กรปกครองส่...,งบอุดหนุน,186720657300
9153,66,กรุงเทพมหานคร,กระทรวงศึกษาธิการ,สำนักงานคณะกรรมการการศึกษาขั้นพื้นฐาน,แผนงานบุคลากรภาครัฐ,ผลผลิต : รายการค่าใช้จ่ายบุคลากรภาครัฐ ยกระดับ...,งบบุคลากร,175000547000
9324,66,กรุงเทพมหานคร,กระทรวงสาธารณสุข,สำนักงานหลักประกันสุขภาพแห่งชาติ,แผนงานยุทธศาสตร์สร้างหลักประกันทางสังคม,ทุนหมุนเวียน : กองทุนหลักประกันสุขภาพแห่งชาติ,งบรายจ่ายอื่น,142297936700
10666,66,จังหวัดนนทบุรี,กระทรวงสาธารณสุข,สำนักงานปลัดกระทรวงสาธารณสุข,แผนงานบุคลากรภาครัฐ,ผลผลิต : รายการค่าใช้จ่ายบุคลากรภาครัฐ พัฒนาด้...,งบบุคลากร,86904159100
9996,66,กรุงเทพมหานคร,ส่วนราชการไม่สังกัดสำนักนายกรัฐมนตรี กระทรวง ห...,สำนักงานตำรวจแห่งชาติ,แผนงานบุคลากรภาครัฐ,ผลผลิต : รายการค่าใช้จ่ายบุคลากรภาครัฐ ปฏิรูปก...,งบบุคลากร,81920476200
4,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานยุทธศาสตร์สร้างหลักประกันทางสังคม,รายจ่ายงบกลาง : ค่าใช้จ่ายในการรักษาพยาบาลข้าร...,งบดำเนินงาน,76000000000
8,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานพื้นฐานด้านการปรับสมดุลและพัฒนาระบบการบร...,รายจ่ายงบกลาง : เงินสำรอง เงินสมทบ และเงินชดเช...,งบอุดหนุน,75980000000
6730,66,กรุงเทพมหานคร,กระทรวงกลาโหม,กองทัพบก,แผนงานบุคลากรภาครัฐ,ผลผลิต : รายการค่าใช้จ่ายบุคลากรภาครัฐ เสริมสร...,งบบุคลากร,49333183100

##ตรวจสอบค่าของตัวแปร Categorical

In [38]:
#จำนวนจังหวัด
df["changwad_area_name"].nunique()

78

In [39]:
#ดูจำนวนรายการแต่ละจังหวัด
df["changwad_area_name"].value_counts()

changwad_area_name
กรุงเทพมหานคร         3907
จังหวัดนนทบุรี         665
จังหวัดเชียงใหม่       349
จังหวัดสงขลา           306
จังหวัดชลบุรี          279
                      ...
จังหวัดสิงห์บุรี       105
จังหวัดสมุทรสาคร       101
จังหวัดอ่างทอง          95
จังหวัดสมุทรสงคราม      88
ส่วนกลาง                16
Name: count, Length: 78, dtype: int64

In [40]:
#จำนวนกระทรวง
df["min_name"].value_counts()

min_name
กระทรวงเกษตรและสหกรณ์                                                                                  2460
กระทรวงศึกษาธิการ                                                                                      2093
กระทรวงการอุดมศึกษา วิทยาศาสตร์ วิจัยและนวัตกรรม                                                       1665
กระทรวงคมนาคม                                                                                          1484
กระทรวงทรัพยากรธรรมชาติและสิ่งแวดล้อม                                                                  1375
จังหวัดและกลุ่มจังหวัด                                                                                 1205
กระทรวงมหาดไทย                                                                                         1099
กระทรวงสาธารณสุข                                                                                       1018
กระทรวงยุติธรรม                                                                                         562
ส่วนราชการไม่สังกัดสำนักนายกรัฐมนตรี กระทรวง หรือทบวง และหน่วยงานภายใต้การควบคุมดูแลของนายกรัฐมนตรี     486
สำนักนายกรัฐมนตรี                                                                                       462
กระทรวงวัฒนธรรม                                                                                         437
กระทรวงการพัฒนาสังคมและความมั่นคงของมนุษย์                                                              375
รัฐวิสาหกิจ                                                                                             374
องค์กรปกครองส่วนท้องถิ่น                                                                                304
กระทรวงพาณิชย์                                                                                          297
กระทรวงการท่องเที่ยวและกีฬา                                                                             270
กระทรวงกลาโหม                                                                                           262
กระทรวงการคลัง                                                                                          238
กระทรวงแรงงาน                                                                                           232
กระทรวงอุตสาหกรรม                                                                                       209
กระทรวงพลังงาน                                                                                          156
กระทรวงดิจิทัลเพื่อเศรษฐกิจและสังคม                                                                     126
หน่วยงานขององค์กรอิสระและองค์กรอัยการ                                                                    93
หน่วยงานของศาล                                                                                           33
กระทรวงการต่างประเทศ                                                                                     24
สภากาชาดไทย                                                                                              22
หน่วยงานของรัฐสภา                                                                                        18
งบกลาง                                                                                                   16
หน่วยงานอื่นของรัฐ                                                                                        6
ทุนหมุนเวียน                                                                                              6
ส่วนราชการในพระองค์                                                                                       1
Name: count, dtype: int64

In [41]:
#ประเภทแผนงาน
df["plan_name"].value_counts()

plan_name
แผนงานพื้นฐานด้านการพัฒนาและเสริมสร้างศักยภาพทรัพยากรมนุษย์                                     2307
แผนงานพื้นฐานด้านการสร้างความสามารถในการแข่งขัน                                                 2181
แผนงานบุคลากรภาครัฐ                                                                             1288
แผนงานยุทธศาสตร์ส่งเสริมการพัฒนาจังหวัดและกลุ่มจังหวัดแบบบูรณาการ                               1205
แผนงานยุทธศาสตร์การเกษตรสร้างมูลค่า                                                              821
                                                                                                ...
แผนงานยุทธศาสตร์พัฒนาและเสริมสร้างการเมืองในระบอบประชาธิปไตยอันมีพระมหากษัตริย์ทรงเป็นประมุข       6
แผนงานยุทธศาสตร์การวิจัยและพัฒนานวัตกรรม                                                           5
แผนงานยุทธศาสตร์พัฒนาศักยภาพด้านวิทยาศาสตร์ เทคโนโลยี และนวัตกรรม                                  4
แผนงานยุทธศาสตร์พัฒนากลไกการบริหารจัดการความมั่นคงแบบองค์รวม                                       4
แผนงานยุทธศาสตร์เพื่อสนับสนุนด้านความมั่นคง                                                        2
Name: count, Length: 61, dtype: int64

In [42]:
#ประเภทค่าใช้จ่าย
df["objc"].value_counts()

objc
งบลงทุน          10013
งบดำเนินงาน       2942
งบอุดหนุน         2759
งบรายจ่ายอื่น      984
งบบุคลากร          710
Name: count, dtype: int64

# เตรียมข้อมูล

## ตาราง GPP เฉพาะปี พ.ศ.2566

In [75]:
# เลือกเฉพาะปี 2566
gpp_2566 = gpp[gpp["TIME_PERIOD"] == 2566]
gpp_2566

,TIME_PERIOD,NA_STAT,NI,AREA,CWT,UNIT_MUL,UNIT,FREQ,Value
28,2566,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์มวลรวมจังหวัด (GPP),ภาคกลาง,ลพบุรี,ล้าน,บาท,รายปี,1.177405e+05
57,2566,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์มวลรวมจังหวัด (GPP),ภาคตะวันออก,สระแก้ว,ล้าน,บาท,รายปี,5.561175e+04
86,2566,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์มวลรวมจังหวัด (GPP),ภาคตะวันออกเฉียงเหนือ,อุบลราชธานี,ล้าน,บาท,รายปี,1.431597e+05
115,2566,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์มวลรวมจังหวัด (GPP),ภาคใต้,นครศรีธรรมราช,ล้าน,บาท,รายปี,1.946688e+05
144,2566,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์ภาค (GRP),กรุงเทพมหานครและปริมณฑล (ปริมณฑล ได้แก่ สมุทรป...,รวม,ล้าน,บาท,รายปี,8.570179e+06
...,...,...,...,...,...,...,...,...,...
7278,2566,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ประชากรทั้งหมด,ภาคตะวันออกเฉียงเหนือ,อุบลราชธานี,พัน,คน,รายปี,1.726992e+03
7307,2566,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ประชากรทั้งหมด,ภาคตะวันออกเฉียงเหนือ,ชัยภูมิ,พัน,คน,รายปี,9.152306e+02
7336,2566,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ประชากรทั้งหมด,ภาคตะวันออกเฉียงเหนือ,บึงกาฬ,พัน,คน,รายปี,3.556091e+02
7365,2566,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์จังหวัด (GPP) ต่อหัว,ภาคใต้,สงขลา,หน่วย,บาท,รายปี,1.477895e+05
7394,2566,ผลิตภัณฑ์มวลรวมในประเทศ ณ ราคาประจำปี,ผลิตภัณฑ์จังหวัด (GPP) ต่อหัว,ภาคใต้,ตรัง,หน่วย,บาท,รายปี,1.117462e+05

## ตาราง งบประมาณ แสดงเฉพาะจังหวัด แผนงาน ประเภทงบประมาณ และ Budget(หน่วย : ล้านบาท)

In [70]:
# เลือกเฉพาะคอลัมน์ที่ต้องการ
budget_df = budget[["changwad_area_name","plan_name",
         "objc","budget"]]

# แปลง Budget เป็นตัวเลข และเปลี่ยนหน่วยเป็นล้านบาท
budget_df["budget"] = pd.to_numeric(budget["budget"], errors="coerce") /1_000_000
budget_df

/tmp/ipykernel_2065/2042864936.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  budget_df["budget"] = pd.to_numeric(budget["budget"], errors="coerce") /1_000_000

,changwad_area_name,plan_name,objc,budget
0,ส่วนกลาง,แผนงานยุทธศาสตร์พัฒนาระบบการเตรียมพร้อมแห่งชาต...,งบรายจ่ายอื่น,2000.0000
1,ส่วนกลาง,แผนงานพื้นฐานด้านความมั่นคง,งบดำเนินงาน,800.0000
2,ส่วนกลาง,แผนงานยุทธศาสตร์เสริมสร้างพลังทางสังคม,งบรายจ่ายอื่น,300.0000
3,ส่วนกลาง,แผนงานยุทธศาสตร์เสริมสร้างพลังทางสังคม,งบลงทุน,2000.0000
4,ส่วนกลาง,แผนงานยุทธศาสตร์สร้างหลักประกันทางสังคม,งบดำเนินงาน,76000.0000
...,...,...,...,...
17403,จังหวัดนราธิวาส,แผนงานยุทธศาสตร์ส่งเสริมการพัฒนาจังหวัดและกลุ่...,งบดำเนินงาน,0.4752
17404,จังหวัดนราธิวาส,แผนงานยุทธศาสตร์ส่งเสริมการกระจายอำนาจให้แก่อง...,งบอุดหนุน,107.2939
17405,จังหวัดนราธิวาส,แผนงานยุทธศาสตร์ส่งเสริมการกระจายอำนาจให้แก่อง...,งบอุดหนุน,299.2114
17406,จังหวัดนราธิวาส,แผนงานยุทธศาสตร์ส่งเสริมการกระจายอำนาจให้แก่อง...,งบอุดหนุน,73.9795
17407,จังหวัดนราธิวาส,แผนงานยุทธศาสตร์ส่งเสริมการกระจายอำนาจให้แก่อง...,งบอุดหนุน,270.3404

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

## ตาราง งบประมาณรวมแต่ละจังหวัด

In [73]:
# เลือกเฉพาะคอลัมน์ที่ต้องการ
df = df[["changwad_area_name", "budget"]]

# แปลง Budget เป็นตัวเลข
df["budget"] = pd.to_numeric(df["budget"], errors="coerce")

# รวมงบประมาณของแต่ละจังหวัด
budget_province = df.groupby("changwad_area_name", as_index=False)["budget"].sum()
budget_province

   changwad_area_name        budget
0       กรุงเทพมหานคร  5.247677e+06
1       จังหวัดกระบี่  5.320809e+03
2    จังหวัดกาญจนบุรี  7.662155e+03
3    จังหวัดกาฬสินธุ์  6.120248e+03
4    จังหวัดกำแพงเพชร  5.683986e+03
..                ...           ...
73   จังหวัดเพชรบูรณ์  6.759399e+03
74         จังหวัดเลย  6.499287e+03
75        จังหวัดแพร่  4.861729e+03
76  จังหวัดแม่ฮ่องสอน  2.754794e+03
77           ส่วนกลาง  5.904700e+05

[78 rows x 2 columns]