<a href="https://colab.research.google.com/github/niradaa-art/project_BP_group8/blob/main/Project_Colab_group8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Group 8 MONEY_knock_everyting
นางสาวณิรดา อนุนิวัฒน์ 673020252-4

นายธนพล ท้าวนอ 673020253-2

นางสาวสุพิชชา คำสิงห์ 673020265-5

นางสาวอาทิติญา ชาชัย 673020270-2

---

#Data
https://drive.google.com/drive/folders/1m6hp8l6iMB1u-a1yNK4laewgrUTy_Bnl?usp=drive_link

#Connect Google Drive

In [1]:
import os
from google.colab import drive
drive.mount('/content/drive')
base_path = '/content/drive/MyDrive/datasets_budget'

Mounted at /content/drive

In [13]:
import pandas as pd

df = pd.read_csv(f"{base_path}/provincial_budget.csv", sep="|")

df

,fy,changwad_area_name,min_name,agc_name,plan_name,output_name,objc,budget
0,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานยุทธศาสตร์พัฒนาระบบการเตรียมพร้อมแห่งชาต...,รายจ่ายงบกลาง : ค่าใช้จ่ายชดใช้เงินทดรองราชการ...,งบรายจ่ายอื่น,2000000000
1,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานพื้นฐานด้านความมั่นคง,รายจ่ายงบกลาง : ค่าใช้จ่ายเกี่ยวกับการเสด็จพระ...,งบดำเนินงาน,800000000
2,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานยุทธศาสตร์เสริมสร้างพลังทางสังคม,รายจ่ายงบกลาง : ค่าใช้จ่ายตามโครงการอันเนื่องม...,งบรายจ่ายอื่น,300000000
3,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานยุทธศาสตร์เสริมสร้างพลังทางสังคม,รายจ่ายงบกลาง : ค่าใช้จ่ายตามโครงการอันเนื่องม...,งบลงทุน,2000000000
4,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานยุทธศาสตร์สร้างหลักประกันทางสังคม,รายจ่ายงบกลาง : ค่าใช้จ่ายในการรักษาพยาบาลข้าร...,งบดำเนินงาน,76000000000
...,...,...,...,...,...,...,...,...
17403,66,จังหวัดนราธิวาส,จังหวัดและกลุ่มจังหวัด,กลุ่มจังหวัดภาคใต้ชายแดน,แผนงานยุทธศาสตร์ส่งเสริมการพัฒนาจังหวัดและกลุ่...,โครงการ : โครงการพัฒนาด้านสังคม,งบดำเนินงาน,475200
17404,66,จังหวัดนราธิวาส,องค์กรปกครองส่วนท้องถิ่น,องค์การบริหารส่วนจังหวัดนราธิวาส,แผนงานยุทธศาสตร์ส่งเสริมการกระจายอำนาจให้แก่อง...,ผลผลิต : ผลผลิตการจัดบริการสาธารณะ,งบอุดหนุน,107293900
17405,66,จังหวัดนราธิวาส,องค์กรปกครองส่วนท้องถิ่น,เทศบาลเมืองนราธิวาส,แผนงานยุทธศาสตร์ส่งเสริมการกระจายอำนาจให้แก่อง...,ผลผลิต : ผลผลิตการจัดบริการสาธารณะ,งบอุดหนุน,299211400
17406,66,จังหวัดนราธิวาส,องค์กรปกครองส่วนท้องถิ่น,เทศบาลเมืองตากใบ,แผนงานยุทธศาสตร์ส่งเสริมการกระจายอำนาจให้แก่อง...,ผลผลิต : ผลผลิตการจัดบริการสาธารณะ,งบอุดหนุน,73979500
17407,66,จังหวัดนราธิวาส,องค์กรปกครองส่วนท้องถิ่น,เทศบาลเมืองสุไหงโก-ลก,แผนงานยุทธศาสตร์ส่งเสริมการกระจายอำนาจให้แก่อง...,ผลผลิต : ผลผลิตการจัดบริการสาธารณะ,งบอุดหนุน,270340400

In [5]:
df.shape

(17408, 8)

In [6]:
df.columns

Index(['fy', 'changwad_area_name', 'min_name', 'agc_name', 'plan_name',
       'output_name', 'objc', 'budget'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17408 entries, 0 to 17407
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   fy                  17408 non-null  int64
 1   changwad_area_name  17408 non-null  object
 2   min_name            17408 non-null  object
 3   agc_name            17408 non-null  object
 4   plan_name           17408 non-null  object
 5   output_name         17408 non-null  object
 6   objc                17408 non-null  object
 7   budget              17408 non-null  int64
dtypes: int64(2), object(6)
memory usage: 1.1+ MB

In [8]:
df.head()

,fy,changwad_area_name,min_name,agc_name,plan_name,output_name,objc,budget
0,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานยุทธศาสตร์พัฒนาระบบการเตรียมพร้อมแห่งชาต...,รายจ่ายงบกลาง : ค่าใช้จ่ายชดใช้เงินทดรองราชการ...,งบรายจ่ายอื่น,2000000000
1,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานพื้นฐานด้านความมั่นคง,รายจ่ายงบกลาง : ค่าใช้จ่ายเกี่ยวกับการเสด็จพระ...,งบดำเนินงาน,800000000
2,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานยุทธศาสตร์เสริมสร้างพลังทางสังคม,รายจ่ายงบกลาง : ค่าใช้จ่ายตามโครงการอันเนื่องม...,งบรายจ่ายอื่น,300000000
3,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานยุทธศาสตร์เสริมสร้างพลังทางสังคม,รายจ่ายงบกลาง : ค่าใช้จ่ายตามโครงการอันเนื่องม...,งบลงทุน,2000000000
4,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานยุทธศาสตร์สร้างหลักประกันทางสังคม,รายจ่ายงบกลาง : ค่าใช้จ่ายในการรักษาพยาบาลข้าร...,งบดำเนินงาน,76000000000

# Clean Data

##ตรวจสอบ Missing Values

In [9]:
df.isnull().sum()

fy                    0
changwad_area_name    0
min_name              0
agc_name              0
plan_name             0
output_name           0
objc                  0
budget                0
dtype: int64

##ตรวจสอบ Duplicate

In [10]:
df.duplicated().sum()

np.int64(1)

In [11]:
df[df.duplicated()] #รายการงบประมาณที่มีข้อมูลเหมือนกันอาจเป็นรายการงบประมาณคนละรายการจริง ๆ

,fy,changwad_area_name,min_name,agc_name,plan_name,output_name,objc,budget
13,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานบริหารเพื่อรองรับกรณีฉุกเฉินหรือจำเป็น,รายจ่ายงบกลาง : เงินสำรองจ่ายเพื่อกรณีฉุกเฉินห...,งบลงทุน,27720000000

##ตรวจสอบข้อมูลผิดปกติ

In [15]:
#ตรวจสอบ columm budget
df["budget"].describe()

count    1.740800e+04
mean     1.828848e+08
std      4.147141e+09
min      1.100000e+03
25%      1.020000e+06
50%      5.856850e+06
75%      3.384408e+07
max      3.227900e+11
Name: budget, dtype: float64

In [16]:
#งบประมาณมีการกระจายค่อนข้างกว้าง
#ตรวจสอบค่า Budget ที่สูงมากก่อนทำ Visualization
df.sort_values("budget", ascending=False).head(10)

,fy,changwad_area_name,min_name,agc_name,plan_name,output_name,objc,budget
5,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานพื้นฐานด้านการปรับสมดุลและพัฒนาระบบการบร...,รายจ่ายงบกลาง : เงินเบี้ยหวัด บำเหน็จ บำนาญ,งบอุดหนุน,322790000000
6916,66,กรุงเทพมหานคร,กระทรวงการคลัง,สำนักงานบริหารหนี้สาธารณะ,แผนงานบริหารจัดการหนี้ภาครัฐ,ผลผลิต : การบริหารการชำระหนี้ของรัฐบาล,งบรายจ่ายอื่น,261756426300
8602,66,กรุงเทพมหานคร,กระทรวงมหาดไทย,กรมส่งเสริมการปกครองท้องถิ่น,แผนงานยุทธศาสตร์ส่งเสริมการกระจายอำนาจให้แก่อง...,ผลผลิต : จัดสรรเงินอุดหนุนให้แก่องค์กรปกครองส่...,งบอุดหนุน,186720657300
9153,66,กรุงเทพมหานคร,กระทรวงศึกษาธิการ,สำนักงานคณะกรรมการการศึกษาขั้นพื้นฐาน,แผนงานบุคลากรภาครัฐ,ผลผลิต : รายการค่าใช้จ่ายบุคลากรภาครัฐ ยกระดับ...,งบบุคลากร,175000547000
9324,66,กรุงเทพมหานคร,กระทรวงสาธารณสุข,สำนักงานหลักประกันสุขภาพแห่งชาติ,แผนงานยุทธศาสตร์สร้างหลักประกันทางสังคม,ทุนหมุนเวียน : กองทุนหลักประกันสุขภาพแห่งชาติ,งบรายจ่ายอื่น,142297936700
10666,66,จังหวัดนนทบุรี,กระทรวงสาธารณสุข,สำนักงานปลัดกระทรวงสาธารณสุข,แผนงานบุคลากรภาครัฐ,ผลผลิต : รายการค่าใช้จ่ายบุคลากรภาครัฐ พัฒนาด้...,งบบุคลากร,86904159100
9996,66,กรุงเทพมหานคร,ส่วนราชการไม่สังกัดสำนักนายกรัฐมนตรี กระทรวง ห...,สำนักงานตำรวจแห่งชาติ,แผนงานบุคลากรภาครัฐ,ผลผลิต : รายการค่าใช้จ่ายบุคลากรภาครัฐ ปฏิรูปก...,งบบุคลากร,81920476200
4,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานยุทธศาสตร์สร้างหลักประกันทางสังคม,รายจ่ายงบกลาง : ค่าใช้จ่ายในการรักษาพยาบาลข้าร...,งบดำเนินงาน,76000000000
8,66,ส่วนกลาง,งบกลาง,งบกลาง,แผนงานพื้นฐานด้านการปรับสมดุลและพัฒนาระบบการบร...,รายจ่ายงบกลาง : เงินสำรอง เงินสมทบ และเงินชดเช...,งบอุดหนุน,75980000000
6730,66,กรุงเทพมหานคร,กระทรวงกลาโหม,กองทัพบก,แผนงานบุคลากรภาครัฐ,ผลผลิต : รายการค่าใช้จ่ายบุคลากรภาครัฐ เสริมสร...,งบบุคลากร,49333183100

##ตรวจสอบค่าของตัวแปร Categorical

In [17]:
#จำนวนจังหวัด
df["changwad_area_name"].nunique()

78

In [18]:
#ดูจำนวนรายการแต่ละจังหวัด
df["changwad_area_name"].value_counts()

changwad_area_name
กรุงเทพมหานคร         3907
จังหวัดนนทบุรี         665
จังหวัดเชียงใหม่       349
จังหวัดสงขลา           306
จังหวัดชลบุรี          279
                      ...
จังหวัดสิงห์บุรี       105
จังหวัดสมุทรสาคร       101
จังหวัดอ่างทอง          95
จังหวัดสมุทรสงคราม      88
ส่วนกลาง                16
Name: count, Length: 78, dtype: int64

In [23]:
#จำนวนกระทรวง
df["min_name"].value_counts()

min_name
กระทรวงเกษตรและสหกรณ์                                                                                  2460
กระทรวงศึกษาธิการ                                                                                      2093
กระทรวงการอุดมศึกษา วิทยาศาสตร์ วิจัยและนวัตกรรม                                                       1665
กระทรวงคมนาคม                                                                                          1484
กระทรวงทรัพยากรธรรมชาติและสิ่งแวดล้อม                                                                  1375
จังหวัดและกลุ่มจังหวัด                                                                                 1205
กระทรวงมหาดไทย                                                                                         1099
กระทรวงสาธารณสุข                                                                                       1018
กระทรวงยุติธรรม                                                                                         562
ส่วนราชการไม่สังกัดสำนักนายกรัฐมนตรี กระทรวง หรือทบวง และหน่วยงานภายใต้การควบคุมดูแลของนายกรัฐมนตรี     486
สำนักนายกรัฐมนตรี                                                                                       462
กระทรวงวัฒนธรรม                                                                                         437
กระทรวงการพัฒนาสังคมและความมั่นคงของมนุษย์                                                              375
รัฐวิสาหกิจ                                                                                             374
องค์กรปกครองส่วนท้องถิ่น                                                                                304
กระทรวงพาณิชย์                                                                                          297
กระทรวงการท่องเที่ยวและกีฬา                                                                             270
กระทรวงกลาโหม                                                                                           262
กระทรวงการคลัง                                                                                          238
กระทรวงแรงงาน                                                                                           232
กระทรวงอุตสาหกรรม                                                                                       209
กระทรวงพลังงาน                                                                                          156
กระทรวงดิจิทัลเพื่อเศรษฐกิจและสังคม                                                                     126
หน่วยงานขององค์กรอิสระและองค์กรอัยการ                                                                    93
หน่วยงานของศาล                                                                                           33
กระทรวงการต่างประเทศ                                                                                     24
สภากาชาดไทย                                                                                              22
หน่วยงานของรัฐสภา                                                                                        18
งบกลาง                                                                                                   16
หน่วยงานอื่นของรัฐ                                                                                        6
ทุนหมุนเวียน                                                                                              6
ส่วนราชการในพระองค์                                                                                       1
Name: count, dtype: int64

In [22]:
#ประเภทแผนงาน
df["plan_name"].value_counts()

plan_name
แผนงานพื้นฐานด้านการพัฒนาและเสริมสร้างศักยภาพทรัพยากรมนุษย์                                     2307
แผนงานพื้นฐานด้านการสร้างความสามารถในการแข่งขัน                                                 2181
แผนงานบุคลากรภาครัฐ                                                                             1288
แผนงานยุทธศาสตร์ส่งเสริมการพัฒนาจังหวัดและกลุ่มจังหวัดแบบบูรณาการ                               1205
แผนงานยุทธศาสตร์การเกษตรสร้างมูลค่า                                                              821
                                                                                                ...
แผนงานยุทธศาสตร์พัฒนาและเสริมสร้างการเมืองในระบอบประชาธิปไตยอันมีพระมหากษัตริย์ทรงเป็นประมุข       6
แผนงานยุทธศาสตร์การวิจัยและพัฒนานวัตกรรม                                                           5
แผนงานยุทธศาสตร์พัฒนาศักยภาพด้านวิทยาศาสตร์ เทคโนโลยี และนวัตกรรม                                  4
แผนงานยุทธศาสตร์พัฒนากลไกการบริหารจัดการความมั่นคงแบบองค์รวม                                       4
แผนงานยุทธศาสตร์เพื่อสนับสนุนด้านความมั่นคง                                                        2
Name: count, Length: 61, dtype: int64

In [21]:
#ประเภทค่าใช้จ่าย
df["objc"].value_counts()

objc
งบลงทุน          10013
งบดำเนินงาน       2942
งบอุดหนุน         2759
งบรายจ่ายอื่น      984
งบบุคลากร          710
Name: count, dtype: int64